### ISSUE TITLE
Page freeze on Windows

### ISSUE THREAD

**Issue by imxood** [tauri-apps/wry#386] opened 2021-08-19 08:59 UTC
**Describe the bug**

After tens of minutes or a few hours, something is unresponsive

**Steps To Reproduce**
```
## Rust uses websocket to send YUV data to the web, and js webgl renders YUV data.

git clone https://github.com/imxood/wry-yuv-sample.git
cd wry-yuv-sample
cargo run
```

**Expected behavior**
```
After tens of minutes or a few hours, rust is ok, js event is ok, css hover is ok, webgl render is ok, and the text is ok
```
**Screenshots**
### normal:

![](https://github.com/imxood/wry-yuv-sample/raw/master/images/test1.png)

### not normal:

1. rust is ok, js event is Ok, css hover is Ok, webgl render is Ok, but the text is gone

![](https://github.com/imxood/wry-yuv-sample/raw/master/images/test2.png)

or:

2. rust is ok, js event is Ok, css hover is Ok, but webgl render is not Ok

![](https://github.com/imxood/wry-yuv-sample/raw/master/images/test3.png)

![](https://github.com/imxood/wry-yuv-sample/raw/master/images/test4.png)

**Platform and Versions (please complete the following information):**
```
host:
    11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.42 GHz
    windows 10

rust:
    nightly-x86_64-pc-windows-msvc
    rustc 1.56.0-nightly (0035d9dce 2021-08-16)

frame:
    wry + actix-web + svelte

MicrosoftEdgeWebView2RuntimeInstallerX64.exe is lastest
```

**Would you assign yourself to resolve this bug?**
- [x] Yes
- [x] No

**Additional context**

**Comment by wusyong** [comment] 2021-08-19 09:37
Please fill the bug report and provide minimum reproducible example, so we could obtain enough information to investigate.

**Comment by imxood** [comment] 2021-08-19 10:00
@wusyong It is not easy to write an example. First describe the situation: Rust and windows10 webview2's js console both work very well, I did the output constantly in rust and develop tools console and render yuv data. but after a while (a little minutes or a little hours) the web page does not respond, other is OK!!
What i am doing is a player, Rust uses websocket to send YUV data to the web, and js webgl renders YUV data.

That's it, do you have any good idea and can you give me some advice? I can take a look at wry or Tao's source code debugging? How can I debug and verify the issue? I have no idea~~

**Comment by wusyong** [comment] 2021-08-19 10:09
You could provide a repo as sample, but it's smaller the better. So we can narrow the scope.
And give detailed step for us to reproduce it. 
Right now I don't have any code or sample to start with. Hence I don't even know what's the real problem is. All I know is something stuck.

**Comment by nothingismagick** [comment] 2021-08-19 10:12
Please provide the results of `tauri info`.

**Comment by nothingismagick** [comment] 2021-08-19 10:14
And what @wusyong is saying is that you should please fill out the template:
![image](https://user-images.githubusercontent.com/35242872/130051575-5554d0ba-777d-473d-a034-e3d42763b726.png)

**Comment by imxood** [comment] 2021-08-19 10:18
@wusyong @nothingismagick well

**Comment by nothingismagick** [comment] 2021-08-19 10:21
The problem is that in this repo we don't know your context. Are you using Tauri? If not, please be clear about your development env / platform.

**Comment by imxood** [comment] 2021-08-21 23:36
@wusyong i add one sample repo https://github.com/imxood/wry-yuv-sample.git, thank you very much for your help

**Comment by wusyong** [comment] 2021-08-23 06:54
Thanks for the repo! I think it's also a good sample for showing how to embed a web server as well.
I think this is also related to [tauri/2496](https://github.com/tauri-apps/tauri/issues/2496) which is really difficult to find the cause.
I couldn't reproduce it yet.
Did you encounter this very frequently? And how is the interval if so?
Could you press F5 and see how it goes if this bug showing again?

Edit: I've been running it for a day but it still doesn't freeze or stuck

**Comment by amrbashir** [comment] 2022-08-30 15:52
Closing this for now since https://github.com/tauri-apps/tauri/issues/2496 is also closed and this hasn't been reported in a while

**Closed as not planned by amrbashir** 2022-08-30 15:52 UTC
Labels: help wanted, type: bug, platform: Windows, status: needs more info
