### ISSUE TITLE
Is it necessary to destroy window when dropping wry::webview::WebView ?

### ISSUE THREAD

**Issue by bg5hfc** [tauri-apps/wry#608] opened 2022-06-14 04:33 UTC
I noticed that the WebView struct implements the Drop trait, and a destroy method is called on `window` when the webview drops(in wry/src/webview/mod.rs).

Is it really necessay because tao::Window has already do the destruction properly on both Linux/mac and Windows platform.

I'm asking this because I wanna build a window with multiple `WebView`s on it (something like the browser with many tabs), but the Drop trait of WebView hinders me.

**Comment by wusyong** [comment] 2022-06-14 06:45
We stick to one window with one webview for simplicity.
We can evaluate multiple webviews support.

**Comment by keiya01** [comment] 2022-06-14 07:18
I agree.
I think window sould be dropped myself in tao layer.

**Comment by keiya01** [comment] 2022-06-17 01:01
If we need to drop window in wry, I think we need to check if window has multi webview🤔

**Comment by amrbashir** [comment] 2022-09-29 17:40
As it stated above, our current api is towards one window with one webview. I am gonna close this as duplicate of #677 as it will be the same fix in the future.

**Closed as not planned by amrbashir** 2022-09-29 17:40 UTC
