### ISSUE TITLE
File DragAndDrop using "drop" eventlistener does not work on Windows

### ISSUE THREAD

**Issue by geolehmann** [tauri-apps/wry#157] opened 2021-04-16 09:19 UTC
**Describe the bug**
As the title says - trying to DragAndDrop files using the "drop" eventlistener does not work, the event is never fired. This is independent of whether I create the webview with a drop handler or not.

**Steps To Reproduce**
Here is a minimal example to reproduce the bevaviour:

```
use wry::{Application, Attributes, Result};

static TEST_HTML: &str = r#"data:text/html,
Drop files onto the red box <br>
<div id="dropZone" style="width: 100px; height: 100px; background-color: red"></div>
<script>
document.getElementById('dropZone').addEventListener('dragover', function(e) {
    e.stopPropagation();
    e.preventDefault();
    e.dataTransfer.dropEffect = 'copy';
});
document.getElementById('dropZone').addEventListener("drop",function (e) {
    e.stopPropagation();
    e.preventDefault();
    console.log(e.dataTransfer.files);
});
</script>
"#;

fn main() -> Result<()> {
  let mut app = Application::new()?;

  app.add_window_with_configs(
    Attributes {
      url: Some(TEST_HTML.to_string()),
      ..Default::default()
    },None,vec![],None)?;
  app.run();
  Ok(())
}
```
The embedded html code works well in a browser, but not in the wry webview.

**Expected behavior**
In the above example, console.log would show the dropped files.

**Platform and Versions (please complete the following information):**
OS: Windows 10
Using wry 0.8.0

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [ ] No

[edited for legibility]

**Comment by nothingismagick** [comment] 2021-04-16 09:30
Using exactly your code I see the console.log on MacOS when I drop.

<img width="789" alt="image" src="https://user-images.githubusercontent.com/35242872/115004345-ff4e1880-9ea6-11eb-884c-eab628fe8b4d.png">

**Comment by wusyong** [comment] 2021-04-16 09:49
Works on linux too. This might be an upstream issue toward webview2.

**Comment by geolehmann** [comment] 2021-04-16 09:51
I´ll test this later this afternoon on another windows machine, to make sure that it is not an issue with my current setup.

**Comment by wusyong** [comment] 2021-04-16 09:56
No need. I can confirm this isn't working on my Windows either.

**Comment by wusyong** [comment] 2021-04-17 10:22
I tested with only winit and it's working. Since we are also moving away from application, I think could close this once winit interface for gtk is merged.

**Comment by wusyong** [comment] 2021-04-20 01:51
Close this because of #163

**Closed as completed by wusyong** 2021-04-20 01:51 UTC
Labels: type: bug, platform: Windows
