### ISSUE TITLE
Blank screen on Windows 10 while trying hello_world

### ISSUE THREAD

**Issue by kamyuentse** [tauri-apps/wry#494] opened 2022-02-11 02:45 UTC
**Describe the bug**

Blank screen on Windows 10 while trying hello_world. Also the window "close" button not work. After I terminating by ctrl-c, the following message printed.
```
[0211/101303.174:ERROR:window_impl.cc(114)] Failed to unregister class Chrome_WidgetWin_0. Error = 0
```

**Steps To Reproduce**

a. fetch repo & execute `cargo run --example hello_world`

**Expected behavior**

shows the https://html5test.com ?

**Screenshots**

**Platform and Versions (please complete the following information):**
OS:  Windows, version 10.0.19041 X64, with Visual Studio Build Tools 2019, WebView2 98.0.1108.43
Rustc: rustc 1.58.1 (db9d1b20b 2022-01-20)

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [ ] No

**Additional context**

**Comment by amrbashir** [comment] 2022-02-28 10:39
> Blank screen on Windows 10 while trying hello_world. Also the window "close" button not work.

I can't reproduce this at all on Windows 11 but I hardly think it makes a difference between 10 and 11. are you using a VM or something? can you take a screenshot?.

> After I terminating by ctrl-c, the following message printed.
> 
> ```
> [0211/101303.174:ERROR:window_impl.cc(114)] Failed to unregister class Chrome_WidgetWin_0. Error = 0
> ```

You can ignore this message, it is irrelevant and related to Webview2.

**Comment by kamyuentse** [comment] 2022-03-05 06:18
> I can't reproduce this at all on Windows 11 but I hardly think it makes a difference between 10 and 11. are you using a VM or something? can you take a screenshot?.

I can not take screenshot for the company workstation. I fail to reproduce on my personal laptop with fresh rust / vs build tools installation. Seems this issue related to specified env / setup.

**Comment by amrbashir** [comment] 2022-03-05 06:49
In this case, I will close this issue until further notice.

**Closed as completed by amrbashir** 2022-03-05 06:49 UTC
Labels: type: bug, platform: Windows

**Comment by ukscone** [comment] 2022-07-22 03:50
I'm running on Win11 and using Ctrl-C or a button with the following code on it 
`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="./lima.css" type="text/css">
    <title>Document</title>
  </head>
  <body>
	<script>
  
//const invoke = window.__TAURI__.invoke;
//const process = window.__TAURI__.process;
const { invoke } = window.__TAURI__.tauri;
const { readTextFile } = window.__TAURI__.fs;
const { exit } = window.__TAURI__.process;

<center>
  <input type="text" id="fname" name="fname" autofocus><br><br>
</center>


<button type="button" id="clickMe">Click Me!</button>

<script>
document.getElementById("clickMe").onclick = function () { exit(1); };

</script>

  </body>
</html>

`

causes this error
`[0721/234350.741:ERROR:window_impl.cc(114)] Failed to unregister class Chrome_WidgetWin_0. Error = 0`

**Comment by ukscone** [comment] 2022-07-22 03:55
actually sort of a false alarm. just tried it without debug console being opened (F12) and no error, with debug console opened it give the error message. did it 3 times with and 3 times without and it was consistent
