### ISSUE TITLE
[Feature] Text find in page

### ISSUE THREAD

**Issue by nawbc** [tauri-apps/wry#1126] opened 2023-12-18 15:56 UTC
We can use `window.find()` as a workaround, but that feature is non-standard. So it's possible to support something like
Electron `contents.findInPage`  [Detail](https://www.electronjs.org/docs/latest/api/web-contents#contentsfindinpagetext-options)

**Comment by FabianLars** [comment] 2023-12-19 17:45
Duplicate of https://github.com/tauri-apps/wry/issues/585. Thanks for the request :)

**Closed as not planned by FabianLars** 2023-12-19 17:45 UTC
