### ISSUE TITLE
Clicking/dragging on images crashes app

### ISSUE THREAD

**Issue by jkelleyrtp** [tauri-apps/wry#452] opened 2021-12-08 07:23 UTC
**Describe the bug**
If I spam click/drag an image then wry crashes for me.

```
2021-12-08 02:20:37.645 desktop[43973:852542] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[15]'
*** First throw call stack:
(
        0   CoreFoundation                      0x00000001b81ac12c __exceptionPreprocess + 240
        1   libobjc.A.dylib                     0x00000001b7efd808 objc_exception_throw + 60
        2   CoreFoundation                      0x00000001b827c464 -[__NSCFString characterAtIndex:].cold.1 + 0
        3   CoreFoundation                      0x00000001b82890a0 -[__NSPlaceholderDictionary initWithCapacity:].cold.1 + 0
        4   CoreFoundation                      0x00000001b80b3e30 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 320
        5   CoreFoundation                      0x00000001b80b3cc4 +[NSDictionary dictionaryWithObjects:forKeys:count:] + 60
        6   VisionKitCore                       0x000000022e55cd4c -[VKAnalyticsAnalyzerEvent coreAnalyticsDictionary] + 1208
        7   VisionKitCore                       0x000000022e51fb1c -[VKAnalyticsProcessor processAndSendEvent:] + 92
        8   VisionKitCore                       0x000000022e5157f4 __69-[VKImageAnalyzer _processRequest:progressHandler:completionHandler:]_block_invoke_2 + 1200
        9   libdispatch.dylib                   0x00000001b7ea0e60 _dispatch_call_block_and_release + 32
        10  libdispatch.dylib                   0x00000001b7ea2bac _dispatch_client_callout + 20
        11  libdispatch.dylib                   0x00000001b7eaa330 _dispatch_lane_serial_drain + 672
        12  libdispatch.dylib                   0x00000001b7eaaea4 _dispatch_lane_invoke + 392
        13  libdispatch.dylib                   0x00000001b7eb5708 _dispatch_workloop_worker_thread + 656
        14  libsystem_pthread.dylib             0x00000001b805d5b0 _pthread_wqthread + 288
        15  libsystem_pthread.dylib             0x00000001b805c2c4 start_wqthread + 8
)
libc++abi: terminating with uncaught exception of type NSException
```

In particular, the img/href I'm using is:

```
img { class: "w-8 h-8 rounded-full object-cover object-right",
    alt: "",
    src: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1050&amp;q=80",
}
```

**Steps To Reproduce**
Make an image with the configuration listed above and the rapidly click on it.

**Expected behavior**
Wry does not crash.

**Platform and Versions (please complete the following information):**
OS: macOS 12.0.1 (21A559)
Rustc: 1.56.1

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No (not sure where to start)

**Comment by lucasfernog** [comment] 2021-12-08 13:42
Duplicate of #2934

**Closed as completed by lucasfernog** 2021-12-08 13:42 UTC
Labels: status: invalid

**Comment by jkelleyrtp** [comment] 2021-12-08 16:15
#2934 is not linking to anything for me. Which issue is that?

**Comment by FabianLars** [comment] 2021-12-08 16:19
https://github.com/tauri-apps/tauri/issues/2934

**Comment by amrbashir** [comment] 2021-12-08 16:19
tauri-apps/tauri#2934

**Comment by lucasfernog** [comment] 2021-12-08 16:33
oops i didn't realize this wasn't on the tauri repo.
